version: '3.7'
services:

  mysql:
    image: mysql:8.0
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3366:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mysql_1
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgresql:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgres
    environment:
      - POSTGRES_DB=postgresql_1
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass